---
version: '3'

tasks:
  init:
    desc: Init the project
    preconditions:
      - test -f secrets.h.tmpl
    cmds:
      - cp secrets.h.tmpl secrets.h
  build:
    desc: Build the project
    cmds:
      - pio run
  clean:
    desc: Clean build files
    cmds:
      - pio run --target clean
  upload:
    desc: Upload the firmware
    cmds:
      - pio run --target upload
  monitor:
    desc: Monitor the serial output
    cmds:
      - pio device monitor
  list-devices:
    desc: List connected serial devices
    cmds:
      - pio device list
  update-packages:
    desc: Update project dependencies
    cmds:
      - pio pkg update
  verbose-build:
    desc: Build with verbose output
    cmds:
      - pio run --verbose
  reset:
    desc: Reset the Dongle by flashing the default fimrware.
    cmds:
      - task: flash
        dir: ./reference/firmware
  default:
    cmds:
      - task -l
    silent: true
