---
version: '3'

tasks:
  compile:
    desc: Compile sketch
    cmds:
      - arduino-cli compile
  dump:
    desc: Dump the profile
    cmds:
      - arduino-cli compile --dump-profile --fqbn esp32:esp32:esp32s3
  list:
    desc: List
    cmds:
      - arduino-cli board list
  monitor:
    desc: Monitor the output
    cmds:
      - arduino-cli monitor
  reset:
    desc: Reset the Dongle by flashing the default fimrware.
    cmds:
      - ./reference/firmware/flash.sh
  update:
    desc: Update index
    cmds:
      - arduino-cli core update-index
  upload:
    desc: Upload the sketch
    cmds:
      - arduino-cli upload
  default:
    cmds:
      - task -l
    silent: true
