---
version: '3'

tasks:
  prune:
    desc: Prune the system
    cmds:
      - pio system prune
  init:
    desc: Init the project
    preconditions:
      - test -f include/secrets.h.tmpl
    cmds:
      - cp include/secrets.h.tmpl include/secrets.h
  encrypt:
    desc: Encrypt secrets.h
    preconditions:
      - test -f include/secrets.h
    cmds:
      - sops -e include/secrets.h > include/secrets.h.enc
  decrypt:
    desc: Decrypt secrets.h
    preconditions:
      - test -f include/secrets.h.enc
    cmds:
      - sops -d include/secrets.h.enc > include/secrets.h
  build:
    desc: Build the project
    cmds:
      - pio run
  clean:
    desc: Clean build files
    cmds:
      - pio run --target clean
  fullclean:
    desc: Perform a full clean of build files
    cmds:
      - pio run --target fullclean
  upload:
    desc: Upload the firmware
    cmds:
      - pio run --target upload
  monitor:
    desc: Monitor the serial output
    cmds:
      - pio device monitor
  list-devices:
    desc: List connected serial devices
    cmds:
      - pio device list
  update-packages:
    desc: Update project dependencies
    cmds:
      - pio pkg update
  verbose-build:
    desc: Build with verbose output
    cmds:
      - pio run --verbose
  reset:
    desc: Reset the Dongle by flashing the default fimrware.
    cmds:
      - task: flash
        dir: ./reference/firmware
  default:
    cmds:
      - task -l
    silent: true
