version: "3"

tasks:
  flash:
    desc: "Flashes the firmware to the ESP32-S3."
    cmds:
      - >
        esptool 
        --chip esp32s3 
        --baud 921600 
        --before default-reset 
        --after hard-reset write-flash -z 
        --flash-mode dio 
        --flash-freq 80m 
        --flash-size 16MB 
        0x0 firmware.bin
